### ISSUE TITLE
Server's certificate expired, Chrome said unsafe.

### ISSUE THREAD

**Issue by wilbeibi** [yuehu/chrome-yuehu#1]
不好意思，我找不到留言的地方就在這提交 issue 了。

**Comment by lepture** [comment]
@Wilbeibi 其实我在等 https://letsencrypt.org/ 的证书。我本地在用 http 的 extension。我发布一个 http 的 extension 吧。

**Comment by lepture** [comment]
@Wilbeibi http 版本的已经发布到 store 里了。0.2.0 应该是正常工作的。

如果你是说网站的话， https 的证书已经过期了，正在等 lets encrypt 的证书。

**Comment by lepture** [comment]
已经开启 cloudflare 的证书。
